name: Push Placeholder Image

on:
  workflow_dispatch:
    inputs:
      image_name:
        description: 'target image name (zenfyrdev/xpost)'
        required: true
        type: string

jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create and Push Placeholder
        run: |
          echo "FROM scratch" > Dockerfile
          echo "LABEL placeholder=true" >> Dockerfile

          docker build -t ${{ github.event.inputs.image_name }}:latest .
          docker push ${{ github.event.inputs.image_name }}:latest
